### ISSUE TITLE
Test suite fails

### ISSUE THREAD

**Issue by remicollet** [llaville/umlwriter#1]
1-8 seems only a order issue (a sort missing ?)
9-14 ???

     + /usr/bin/phpunit -v
     PHPUnit 4.5.1 by Sebastian Bergmann and contributors.
     Configuration read from /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/phpunit.xml.dist
     FFFFFEFFFFFFFEFF
     Time: 58 ms, Memory: 9.25Mb
     There were 2 errors:
     1) Bartlett\Tests\UmlWriter\ProcessorTest::testGraphvizProcessor with data set #5 ('/builddir/build/BUILD/umlwrit...ts.php', 'digraph G1 {\n	overlap = false..."];\n}\n')
     Array to string conversion
     /usr/share/php/Bartlett/Reflect/Model/ClassModel.php:105
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/src/Bartlett/UmlWriter/Processor/AbstractProcessor.php:187
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/src/Bartlett/UmlWriter/Processor/AbstractProcessor.php:113
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:99
     2) Bartlett\Tests\UmlWriter\ProcessorTest::testPlantUMLProcessor with data set #5 ('/builddir/build/BUILD/umlwrit...ts.php', '	interface OneInterface << in...rface\n')
     Array to string conversion
     /usr/share/php/Bartlett/Reflect/Model/ClassModel.php:105
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/src/Bartlett/UmlWriter/Processor/AbstractProcessor.php:187
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/src/Bartlett/UmlWriter/Processor/AbstractProcessor.php:113
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:119
     --
     There were 14 failures:
     1) Bartlett\Tests\UmlWriter\ProcessorTest::testGraphvizProcessor with data set #0 ('/builddir/build/BUILD/umlwrit...ty.php', 'digraph G1 {\n	overlap = false...\n	}\n}\n')
     Failed asserting that two strings are equal.
     --- Expected
     +++ Actual
     @@ @@
      'digraph G1 {
      	overlap = false;
      	node [fontname="Verdana", fontsize="8", shape="none", margin="0", fillcolor="#FEFECE", style="filled"];
      	edge [fontname="Verdana", fontsize="8"];
     -	subgraph cluster_7 {
     +	subgraph cluster_0 {
      		label="";
      		"OneClass" [label=<
      <table border="0" cellborder="1" cellspacing="0">
      <tr><td align="center">&lt;&lt; <font color="black"><i>class</i></font> &gt;&gt;<br/><b>OneClass</b></td></tr>
      <tr><td><table border="0" cellspacing="0" cellpadding="2">
      <tr><td align="left">- stringProperty</td></tr>
      <tr><td align="left"># intProperty</td></tr>
      <tr><td align="left">+ booleanProperty</td></tr>
      <tr><td align="left"># arrayProperty</td></tr>
      <tr><td align="left">+ floatProperty</td></tr>
      </table></td></tr>
      <tr><td> </td></tr>
      </table>
      >];
      	}
      }
      '
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:101
     2) Bartlett\Tests\UmlWriter\ProcessorTest::testGraphvizProcessor with data set #1 ('/builddir/build/BUILD/umlwrit...nt.php', 'digraph G1 {\n	overlap = false...s";\n}\n')
     Failed asserting that two strings are equal.
     --- Expected
     +++ Actual
     @@ @@
      'digraph G1 {
      	overlap = false;
      	node [fontname="Verdana", fontsize="8", shape="none", margin="0", fillcolor="#FEFECE", style="filled"];
      	edge [fontname="Verdana", fontsize="8"];
     -	subgraph cluster_6 {
     +	subgraph cluster_1 {
      		label="";
      		"ParentClass" [label=<
      <table border="0" cellborder="1" cellspacing="0">
      <tr><td align="center">&lt;&lt; <font color="black"><i>class</i></font> &gt;&gt;<br/><b>ParentClass</b></td></tr>
      <tr><td><table border="0" cellspacing="0" cellpadding="2">
      <tr><td align="left">+ PARENT_CONSTANT</td></tr>
      <tr><td align="left">+ INHERIT_CONSTANT</td></tr>
      </table></td></tr>
      <tr><td> </td></tr>
      </table>
      >];
      		"ExtendingClass" [label=<
      <table border="0" cellborder="1" cellspacing="0">
      <tr><td align="center">&lt;&lt; <font color="black"><i>class</i></font> &gt;&gt;<br/><b>ExtendingClass</b></td></tr>
      <tr><td><table border="0" cellspacing="0" cellpadding="2">
      <tr><td align="left">+ PARENT_CONSTANT</td></tr>
      </table></td></tr>
      <tr><td> </td></tr>
      </table>
      >];
      	}
      	"ExtendingClass" -> "ParentClass";
      }
      '
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:101
     3) Bartlett\Tests\UmlWriter\ProcessorTest::testGraphvizProcessor with data set #2 ('/builddir/build/BUILD/umlwrit...nt.php', 'digraph G1 {\n	overlap = false...\n	}\n}\n')
     Failed asserting that two strings are equal.
     --- Expected
     +++ Actual
     @@ @@
      'digraph G1 {
      	overlap = false;
      	node [fontname="Verdana", fontsize="8", shape="none", margin="0", fillcolor="#FEFECE", style="filled"];
      	edge [fontname="Verdana", fontsize="8"];
     -	subgraph cluster_5 {
     +	subgraph cluster_2 {
      		label="";
      		"OneClass" [label=<
      <table border="0" cellborder="1" cellspacing="0">
      <tr><td align="center">&lt;&lt; <font color="black"><i>class</i></font> &gt;&gt;<br/><b>OneClass</b></td></tr>
      <tr><td><table border="0" cellspacing="0" cellpadding="2">
      <tr><td align="left">+ STRING_CONSTANT</td></tr>
      <tr><td align="left">+ INTEGER_CONSTANT</td></tr>
      <tr><td align="left">+ FLOAT_CONSTANT</td></tr>
      <tr><td align="left">+ LF_CONSTANT</td></tr>
      <tr><td align="left">+ CR_CONSTANT</td></tr>
      <tr><td align="left">+ TAB_CONSTANT</td></tr>
      <tr><td align="left">+ NOVALUE_STATIC</td></tr>
      <tr><td align="left">+ STRING_STATIC</td></tr>
      <tr><td align="left">+ INTEGER_STATIC</td></tr>
      <tr><td align="left">+ FLOAT_STATIC</td></tr>
      <tr><td align="left">+ LF_STATIC</td></tr>
      <tr><td align="left">+ CR_STATIC</td></tr>
      <tr><td align="left">+ TAB_STATIC</td></tr>
      <tr><td align="left">+ PUBLIC_STATIC</td></tr>
      <tr><td align="left"># PROTECTED_STATIC</td></tr>
      <tr><td align="left">- PRIVATE_STATIC</td></tr>
      </table></td></tr>
      <tr><td><table border="0" cellspacing="0" cellpadding="2">
      <tr><td align="left">+<u>staticPublic</u>()</td></tr>
      <tr><td align="left">#<u>staticProtected</u>()</td></tr>
      <tr><td align="left">-<u>staticPrivate</u>()</td></tr>
      </table></td></tr>
      </table>
      >];
      	}
      }
      '
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:101
     4) Bartlett\Tests\UmlWriter\ProcessorTest::testGraphvizProcessor with data set #3 ('/builddir/build/BUILD/umlwrit...od.php', 'digraph G1 {\n	overlap = false...s";\n}\n')
     Failed asserting that two strings are equal.
     --- Expected
     +++ Actual
     @@ @@
      'digraph G1 {
      	overlap = false;
      	node [fontname="Verdana", fontsize="8", shape="none", margin="0", fillcolor="#FEFECE", style="filled"];
      	edge [fontname="Verdana", fontsize="8"];
     -	subgraph cluster_4 {
     +	subgraph cluster_3 {
      		label="";
      		"ParentClass" [label=<
      <table border="0" cellborder="1" cellspacing="0">
      <tr><td align="center">&lt;&lt; <font color="black"><i>class</i></font> &gt;&gt;<br/><b>ParentClass</b></td></tr>
      <tr><td> </td></tr>
      <tr><td><table border="0" cellspacing="0" cellpadding="2">
      <tr><td align="left">+someParentMethod()</td></tr>
      <tr><td align="left">+methodToOverride()</td></tr>
      </table></td></tr>
      </table>
      >];
      		"ExtendingClass" [label=<
      <table border="0" cellborder="1" cellspacing="0">
      <tr><td align="center">&lt;&lt; <font color="black"><i>class</i></font> &gt;&gt;<br/><b>ExtendingClass</b></td></tr>
      <tr><td> </td></tr>
      <tr><td><table border="0" cellspacing="0" cellpadding="2">
      <tr><td align="left">+methodToOverride()</td></tr>
      </table></td></tr>
      </table>
      >];
      	}
      	"ExtendingClass" -> "ParentClass";
      }
      '
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:101
     5) Bartlett\Tests\UmlWriter\ProcessorTest::testGraphvizProcessor with data set #4 ('/builddir/build/BUILD/umlwrit...od.php', 'digraph G1 {\n	overlap = false...\n	}\n}\n')
     Failed asserting that two strings are equal.
     --- Expected
     +++ Actual
     @@ @@
      'digraph G1 {
      	overlap = false;
      	node [fontname="Verdana", fontsize="8", shape="none", margin="0", fillcolor="#FEFECE", style="filled"];
      	edge [fontname="Verdana", fontsize="8"];
     -	subgraph cluster_3 {
     +	subgraph cluster_4 {
      		label="";
      		"OneClass" [label=<
      <table border="0" cellborder="1" cellspacing="0">
      <tr><td align="center">&lt;&lt; <font color="black"><i>class</i></font> &gt;&gt;<br/><b>OneClass</b></td></tr>
      <tr><td> </td></tr>
      <tr><td><table border="0" cellspacing="0" cellpadding="2">
      <tr><td align="left">+zeroMethod()</td></tr>
      <tr><td align="left">+objectTypeHint()</td></tr>
      <tr><td align="left">+objectTypeHintAndDocComment()</td></tr>
      <tr><td align="left">#scalarParameters()</td></tr>
      <tr><td align="left">-typeHintWinsOverDocComment()</td></tr>
      <tr><td align="left">+parametersWithValues()</td></tr>
      </table></td></tr>
      </table>
      >];
      	}
      }
      '
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:101
     6) Bartlett\Tests\UmlWriter\ProcessorTest::testGraphvizProcessor with data set #6 ('/builddir/build/BUILD/umlwrit...ds.php', 'digraph G1 {\n	overlap = false...s";\n}\n')
     Failed asserting that two strings are equal.
     --- Expected
     +++ Actual
     @@ @@
      'digraph G1 {
      	overlap = false;
      	node [fontname="Verdana", fontsize="8", shape="none", margin="0", fillcolor="#FEFECE", style="filled"];
      	edge [fontname="Verdana", fontsize="8"];
     -	subgraph cluster_1 {
     +	subgraph cluster_5 {
      		label="";
      		"OneClass" [label=<
      <table border="0" cellborder="1" cellspacing="0">
      <tr><td align="center">&lt;&lt; <font color="black"><i>class</i></font> &gt;&gt;<br/><b>OneClass</b></td></tr>
      <tr><td> </td></tr>
      <tr><td> </td></tr>
      </table>
      >];
      		"TwoClass" [label=<
      <table border="0" cellborder="1" cellspacing="0">
      <tr><td align="center">&lt;&lt; <font color="black"><i>class</i></font> &gt;&gt;<br/><b>TwoClass</b></td></tr>
      <tr><td> </td></tr>
      <tr><td> </td></tr>
      </table>
      >];
      	}
      	"TwoClass" -> "OneClass";
      }
      '
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:101
     7) Bartlett\Tests\UmlWriter\ProcessorTest::testGraphvizProcessor with data set #7 ('/builddir/build/BUILD/umlwrit...ss.php', 'digraph G1 {\n	overlap = false...\n	}\n}\n')
     Failed asserting that two strings are equal.
     --- Expected
     +++ Actual
     @@ @@
      'digraph G1 {
      	overlap = false;
      	node [fontname="Verdana", fontsize="8", shape="none", margin="0", fillcolor="#FEFECE", style="filled"];
      	edge [fontname="Verdana", fontsize="8"];
     -	subgraph cluster_0 {
     +	subgraph cluster_6 {
      		label="";
      		"OneClass" [label=<
      <table border="0" cellborder="1" cellspacing="0">
      <tr><td align="center">&lt;&lt; <font color="black"><i>class</i></font> &gt;&gt;<br/><b>OneClass</b></td></tr>
      <tr><td> </td></tr>
      <tr><td> </td></tr>
      </table>
      >];
      	}
      }
      '
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:101
     8) Bartlett\Tests\UmlWriter\ProcessorTest::testPlantUMLProcessor with data set #0 ('/builddir/build/BUILD/umlwrit...ty.php', '	class OneClass << class >> {...ty\n	}\n')
     Failed asserting that two strings are equal.
     --- Expected
     +++ Actual
     @@ @@
     -'	class OneClass << class >> {
     +'@startuml
     +	class OneClass << class >> {
     @@ @@
      	}
     +@enduml
      '
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:121
     9) Bartlett\Tests\UmlWriter\ProcessorTest::testPlantUMLProcessor with data set #1 ('/builddir/build/BUILD/umlwrit...nt.php', '	class ParentClass << class >...Class\n')
     Failed asserting that two strings are equal.
     --- Expected
     +++ Actual
     @@ @@
     -'	class ParentClass << class >> {
     +'@startuml
     +	class ParentClass << class >> {
     @@ @@
      ExtendingClass --|> ParentClass
     +@enduml
      '
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:121
     10) Bartlett\Tests\UmlWriter\ProcessorTest::testPlantUMLProcessor with data set #2 ('/builddir/build/BUILD/umlwrit...nt.php', '	class OneClass << class >> {...()\n	}\n')
     Failed asserting that two strings are equal.
     --- Expected
     +++ Actual
     @@ @@
     -'	class OneClass << class >> {
     +'@startuml
     +	class OneClass << class >> {
     @@ @@
      	}
     +@enduml
      '
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:121
     11) Bartlett\Tests\UmlWriter\ProcessorTest::testPlantUMLProcessor with data set #3 ('/builddir/build/BUILD/umlwrit...od.php', '	class ParentClass << class >...Class\n')
     Failed asserting that two strings are equal.
     --- Expected
     +++ Actual
     @@ @@
     -'	class ParentClass << class >> {
     +'@startuml
     +	class ParentClass << class >> {
     @@ @@
      ExtendingClass --|> ParentClass
     +@enduml
      '
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:121
     12) Bartlett\Tests\UmlWriter\ProcessorTest::testPlantUMLProcessor with data set #4 ('/builddir/build/BUILD/umlwrit...od.php', '	class OneClass << class >> {...()\n	}\n')
     Failed asserting that two strings are equal.
     --- Expected
     +++ Actual
     @@ @@
     -'	class OneClass << class >> {
     +'@startuml
     +	class OneClass << class >> {
     @@ @@
      	}
     +@enduml
      '
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:121
     13) Bartlett\Tests\UmlWriter\ProcessorTest::testPlantUMLProcessor with data set #6 ('/builddir/build/BUILD/umlwrit...ds.php', '	class OneClass << class >> {...Class\n')
     Failed asserting that two strings are equal.
     --- Expected
     +++ Actual
     @@ @@
     -'	class OneClass << class >> {
     +'@startuml
     +	class OneClass << class >> {
      	}
      	class TwoClass << class >> {
      	}
      TwoClass --|> OneClass
     +@enduml
      '
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:121
     14) Bartlett\Tests\UmlWriter\ProcessorTest::testPlantUMLProcessor with data set #7 ('/builddir/build/BUILD/umlwrit...ss.php', '	class OneClass << class >> {\n	}\n')
     Failed asserting that two strings are equal.
     --- Expected
     +++ Actual
     @@ @@
     -'	class OneClass << class >> {
     +'@startuml
     +	class OneClass << class >> {
      	}
     +@enduml
      '
     /builddir/build/BUILD/umlwriter-48f1e73fd3716824830185342319e8217e87cc3e/tests/ProcessorTest.php:121
     FAILURES!
     Tests: 16, Assertions: 14, Failures: 14, Errors: 2.

**Comment by llaville** [comment]
I'll check it. I'm currently given the final touch, on user doc and unit tests

**Comment by llaville** [comment]
Reason came from [commit](https://github.com/llaville/umlwriter/commit/48f1e73fd3716824830185342319e8217e87cc3e), test units were not updated after that.

I've run a local test suite pass, and it was ok. I'll push it to repo

**Comment by remicollet** [comment]
I confirm 9-14 are fixed
Still the order issue (1-8)

**Comment by llaville** [comment]
Tell me if by adding a `asort($graphs);` expression before https://github.com/llaville/umlwriter/blob/master/tests/ProcessorTest.php#L61 that solve the order issue

**Comment by remicollet** [comment]
Yes, adding the asort fix the test result

     $ phpunit
     PHPUnit 4.5.1 by Sebastian Bergmann and contributors.
     
     Configuration read from /tmp/umlwriter/phpunit.xml.dist
     
     ................
     
     Time: 162 ms, Memory: 10,75Mb
     
     OK (16 tests, 16 assertions)

**Comment by llaville** [comment]
Fix commited. See https://github.com/llaville/umlwriter/commit/dd58a0b71894693250839ad7c7538a7510758a3b
