### ISSUE TITLE
Default path and output name

### ISSUE THREAD

**Issue by ages96** [llaville/umlwriter#11]
Hi, I am trying to find a third party package to generate Class Diagrams, I am interested in this package because the extracted output extends as needed, but when I successfully execute  `umlwriter diagram: render --reflector = reflect --processor = graphviz /path/to/myproject`, I do not know where the default output is, and can i manually customized the output path ?

Thank you very much

**Comment by llaville** [comment]
Hello,
Result is displayed by default on standard output. And if you want to send result to a file, use the `>` redirection operator.

**Comment by ages96** [comment]
Got it, that means for output is the output from the terminal directly huh?, I think there is an output of pdf or html files automatically. Thank you
