### ISSUE TITLE
How to generate the chart automatically?

### ISSUE THREAD

**Issue by renatoschroepfer** [llaville/umlwriter#13]
I am using `Ubuntu 18.04` and did install UmlWriter and php reflect.

However, when I run the command on the terminal, only one html file is generated and not the diagram. My question is how to generate the diagram automatically from a direct and save it to a destination folder.

I am using these versions below at the moment.

```
mlWriter version 1.2.0
dot - graphviz version 2.40.1 (20161225.0304)
phpReflect version 4.2.2
```

Command I'm using on terminal

> umlwriter diagram:render --reflector=reflect --processor=graphviz src

I want to generate output with the diagram in the destination folder.

Example:
`umlwriter diagram:render --reflector=reflect --processor=graphviz src   /dist/diagram.png`

**Comment by llaville** [comment]
Hello,
Diagram generation is explained in official doc, built in html format : 
see it at http://php5.laurent-laville.org/umlwriter/manual/current/en/getting-started.html

You can automate this by combining two commands with redirect command output to file and launch the dot or java plantuml executable.

Hope it will help you
