### ISSUE TITLE
Can not install 2.0.0-rc1 with composer

### ISSUE THREAD

**Issue by koengabriels** [llaville/umlwriter#14]
``composer require bartlett/umlwriter 2.0.0-rc1``
 gives the following output/error:

```
./composer.json` has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bartlett/umlwriter 2.0.0-rc1 -> satisfiable by bartlett/umlwriter[2.0.0-rc.1].
    - bartlett/umlwriter 2.0.0-rc.1 requires bartlett/graph-plantuml-generator 1.0.0-rc.1 -> satisfiable by bartlett/graph-plantuml-generator[1.0.0-rc.1] but these conflict with your requirements or minimum-stability.


Installation failed, deleting ./composer.json.
```

**Comment by llaville** [comment]
Hello @koengabriels 

Explains was given in https://github.com/llaville/umlwriter/issues/8#issuecomment-626492719.
But it's not enough now, that graphp/graph project changed (see https://github.com/llaville/graph-uml/issues/1)

If you want to install the 2.0.0-rc1 before waiting a RC2, you must define your composer.json as follow  

```json
{
  "require": {
    "bartlett/umlwriter": "2.x-dev",
    "graphp/graph": "dev-master#0d78233",
    "graphp/graphviz": "dev-subgraph_cluster_attributes",
    "symfony/finder": "^4.4|^5.0"
  },
  "minimum-stability": "dev",
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/llaville/graphviz"
    }
  ]
}
```

**Comment by koengabriels** [comment]
Thank you for the quick response!
I will give this a go, I am looking to include automated UML generation in our development process and your project seems to fit the bill so I'll be testing with the release candidates and once version 2 is stable/mature we'll probably implement it in our toolchain.

**Comment by llaville** [comment]
Be aware that the version 2.0 of umlwriter will be mature only when `graphp/graph` will reach its first stable version 1.0

**Comment by koengabriels** [comment]
Thanks for the headsup
