### ISSUE TITLE
Runtime issue

### ISSUE THREAD

**Issue by remicollet** [llaville/umlwriter#2]
$ umlwriter diagram:render --processor reflect --processor graphviz .
     
     Fatal error: Call to undefined method Bartlett\Reflect\Model\FunctionModel::isTrait() in /usr/share/php/Bartlett/UmlWriter/Processor/AbstractProcessor.php on line 163
     
     Call Stack:
         0.0001     500376   1. {main}() /usr/bin/umlwriter:0
         0.0057    1993488   2. Symfony\Component\Console\Application->run() /usr/bin/umlwriter:36
         0.0074    2379256   3. Symfony\Component\Console\Application->doRun() /usr/share/php/Symfony/Component/Console/Application.php:124
         0.0074    2380144   4. Symfony\Component\Console\Application->doRunCommand() /usr/share/php/Symfony/Component/Console/Application.php:193
         0.0074    2380616   5. Symfony\Component\Console\Command\Command->run() /usr/share/php/Symfony/Component/Console/Application.php:889
         0.0076    2385296   6. Bartlett\UmlWriter\Console\Command\DiagramRender->execute() /usr/share/php/Symfony/Component/Console/Command/Command.php:253
         0.0496    7610352   7. Bartlett\UmlWriter\Processor\AbstractProcessor->render() /usr/share/php/Bartlett/UmlWriter/Console/Command/DiagramRender.php:99
         0.0497    7613888   8. Bartlett\UmlWriter\Processor\AbstractProcessor->writeObjectElement() /usr/share/php/Bartlett/UmlWriter/Processor/AbstractProcessor.php:113

**Comment by remicollet** [comment]
Tested with phpreflect 3.0.0dev revison 2c88d1a

**Comment by llaville** [comment]
Remi,
Can you specify what source you analyze. I got no error on my side !

**Comment by remicollet** [comment]
> Can you specify what source you analyze.
doctrine/instantiator 1.0.4

**Comment by llaville** [comment]
Found notice errors produced by php-reflect on symfony/console 2.5.10 (so a fix is required), but I got no error on doctrine/instantiator 1.0.4 (strange for this last case)

**Comment by llaville** [comment]
Symfony/Console produced error when analysing source code but found unit tests. This is of course a bad practice to mixed source code and unit test cases ( but it's not my fault here ).

So when php-reflect analyse source test ( I did not test it myself since a long time, so it's my fault here ), it raise a notice error 

Notice: Undefined property: PhpParser\Node\Name\FullyQualified::$name in php-reflect\src\Bartlett\Reflect\Analyser\AbstractAnalyser.php on line 159

I'll push a fix on php-reflect right away !

**Comment by llaville** [comment]
Update your copy. With php-reflect commit https://github.com/llaville/php-reflect/commit/8ca26b0c84316648d5f3c1924059580109be0e9f, all should be fine now.

Thanks Remi for your feedback

**Comment by llaville** [comment]
And I understand now, probably, why I'm not error on doctrine/instantiator.  In this case I'av analysed only source code, and not full package that include unit tests (but distinct from source : good practice)

**Comment by remicollet** [comment]
Notice: I run the test in the sources tree without the tests.

Update 

       - Updating bartlett/php-reflect 3.0.x-dev (342c12f => 8ca26b0)
         The package has modified files:
         M bin/phpreflect
         Discard changes [y,n,v,s,?]? y
         Checking out 8ca26b0c84316648d5f3c1924059580109be0e9f

Test, same error:

     $ php /tmp/umlwriter/bin/umlwriter diagram:render --reflector=reflect --processor=graphviz .
     
     Fatal error: Call to undefined method Bartlett\Reflect\Model\FunctionModel::isTrait() in /tmp/umlwriter/src/Bartlett/UmlWriter/Processor/AbstractProcessor.php on line 163

**Comment by llaville** [comment]
Strange behavior: I've got no such error, but a more readable (that tell me something)

PHP Notice:  Undefined property: PhpParser\Node\Stmt\Trait_::$extends in umlwriter\vendor\bartlett\php-reflect\src\Bartlett\Reflect\Model\ClassModel.php on line 104

Another cas to fix in php-reflect.  Migration to nikic/php-parser 1.2.1 (+patch), let me discover some new bugs, that I won't see before. Of course it's on my side !

**Comment by llaville** [comment]
Use php-reflect with new commit https://github.com/llaville/php-reflect/commit/7efd1d03583b32d8970100b5b8dc2dfd15b213e8

**Comment by llaville** [comment]
I've invoke umlwriter diagram:render command on full contents of doctrine/instantiator 1.0.4 (that have Trait), and symfony/console 2.5.10 (that have unit tests inside source code), and don't see any other notice errors.

**Comment by remicollet** [comment]
Updating bartlett/php-reflect 3.0.x-dev (8ca26b0 => 7efd1d0)

Same issue.

**Comment by llaville** [comment]
Same source code analysed ?

**Comment by remicollet** [comment]
Yes, doctrine/instantiator

**Comment by remicollet** [comment]
It seems the error comes from the generated autoloader in the doctrine/instantor code which is a closure

   $ phpab --output sources/autoload.php  sources

This file contains:

     <?php
     // @codingStandardsIgnoreFile
     // @codeCoverageIgnoreStart
     // this is an autogenerated file - do not edit
     spl_autoload_register(
         function($class) {
             static $classes = null;
             if ($classes === null) {
                 $classes = array(
                     'doctrine\\instantiator\\exception\\exceptioninterface' => '/Exception/ExceptionInterface.php',
                     'doctrine\\instantiator\\exception\\invalidargumentexception' => '/Exception/InvalidArgumentException.php',
                     'doctrine\\instantiator\\exception\\unexpectedvalueexception' => '/Exception/UnexpectedValueException.php',
                     'doctrine\\instantiator\\instantiator' => '/Instantiator.php',
                     'doctrine\\instantiator\\instantiatorinterface' => '/InstantiatorInterface.php'
                 );
             }
             $cn = strtolower($class);
             if (isset($classes[$cn])) {
                 require __DIR__ . $classes[$cn];
             }
         }
     );
     // @codeCoverageIgnoreEnd

**Comment by llaville** [comment]
Well, as this code is not include in source code distrib, this is the reason I can't reproduce issue

**Comment by llaville** [comment]
Ok found origin of issue ! 
In `AbstractProcessor`, and common `render()` method, when we proceed all objects grabbed from reverse-engine that include (class, interface, trait, but also user function and closure).

No way on UML class diagram for functions, so I'll fix this time only the umlWriter

**Comment by llaville** [comment]
This affect only the Bartlett\Reflect reflector and not TokenReflection (cool ;-)

**Comment by llaville** [comment]
Ok this time we should got it !

**Comment by llaville** [comment]
at one details ... forget to filter classes collection on user function and closure : see commit https://github.com/llaville/umlwriter/commit/4b6624000a23b45c46f280eb366fc38faa8ce9a6

**Comment by remicollet** [comment]
Thanks, I confirm the issue is fixed.

**Comment by llaville** [comment]
Nice to hear :)
