### ISSUE TITLE
Docker pull isn't working

### ISSUE THREAD

**Issue by mtaku3** [llaville/umlwriter#24]
# Bug report category

- [x] Installation issue.
- [ ] Feature issue.
- [ ] Other. Please specify in `Summary` section

## Summary
Docker pull isn't working. And seems to be a permission issue.

## Expected behaviour
When
```bash
docker pull ghcr.io/llaville/umlwriter:v3
```
it should successfully pull the container image.

## Actual behaviour
When
```bash
docker pull ghcr.io/llaville/umlwriter:v3
```
it returns
```bash
Error response from daemon: Head "https://ghcr.io/v2/llaville/umlwriter/manifests/v3": unauthorized
```

**Comment by llaville** [comment]
Hello @mtaku3 
Can you please try it again, because it seems to come from GitHub host itself. 

Alternative problem, is that you've authenticated to ghcr.io with a now-expired token ? 
Perhaps try `docker logout ghcr.io` and then pull again ?

**Comment by mtaku3** [comment]
> Hello @mtaku3 Can you please try it again, because it seems to come from GitHub host itself.
> 
> Alternative problem, is that you've authenticated to ghcr.io with a now-expired token ? Perhaps try `docker logout ghcr.io` and then pull again ?

Hi, I logged out from ghcr.io and tried to pull again, but the result was the same.
FYI, other ghcr.io containers (like `ghcr.io/oracle/oraclelinux8-php:7.4-fpm-20230510`) could be pulled successfully.

**Comment by llaville** [comment]
Ok, it was fixed now ! My Package on ghcr.io was declared as private. I've changed visibility to public.

**Comment by mtaku3** [comment]
Confirmed.

Thanks a lot!
