### ISSUE TITLE
Missing class Uncaught Error: Class "Bartlett\Reflect\Client" not found in 

### ISSUE THREAD

**Issue by phackwer** [llaville/umlwriter#25]
Having lots of error (including missing classes) on PHP 8.2.6. I ran the command as follows:

./vendor/bin/umlwriter diagram:render --processor PlantUml hc8/

I do have graphviz dot and plantuml on my path, and they work fine from IntelliJ, so... What really surprised me is the missing class in the error messages.

PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/phackwer/Projects/amnexis-hc8/vendor/symfony/console/Helper/HelperSet.php on line 104

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/phackwer/Projects/amnexis-hc8/vendor/symfony/console/Helper/HelperSet.php on line 104

PHP Fatal error:  Uncaught Error: Class "Bartlett\Reflect\Client" not found in /Users/phackwer/Projects/amnexis-hc8/vendor/bartlett/umlwriter/src/Bartlett/UmlWriter/Reflector/Reflect.php:43
Stack trace:

**Comment by llaville** [comment]
Please, precise what versions you used and how you've installed it (composer / docker / phar ) ?

Results of  `composer show` after installation (if by Composer) will help too !

**Comment by llaville** [comment]
It seems that you uses an un-maintained version 1.x ! 
If I'm wrong please correct me and re-open this issue. And/Or upgrade to version 3.x that is the latest especially for PHP 8.2 !
