### ISSUE TITLE
`ReflectionException` Exception raise after utilize `diagram:class`.

### ISSUE THREAD

**Issue by realFranco** [llaville/umlwriter#26]
First of all, thank you for your repo umlwriter. I didn't  successfully try it yet but I appreciate your effort 👋

# Bug report category
- [x] Feature issue.

## Disclaimer:
- In the past, an issue was open related to the same: https://github.com/llaville/umlwriter/issues/23
- I have been using PHP for less than 10 days, so I do not have to much context about packaging and software distribution around the PHP ecosystem and Symphony advanced concepts.

## Target:

Make use of `umlwriter` in order to apply reverse engineering, given a directory with OOP PHP source code written in Symphony `^4.4.50` and avialable for PHP `7.4 && 8.1`, create UML diagram clases, I successfully do this using Visual Paradigm through the "Instant Reverse" tool but that is definitely another story.

## Evidence:

The evidence is structured in this way, I'll try to add all the information that I consider pertinent, I hope some of you can replicate the current problem that I am facing right now:

 - [Environment and project structure](#environment-and-project-structure)
 - [Hands on and output](#hands-on-and-output)
 - [References](#references)

### Environment and project structure

  ARM based: M1 Pro chip.

  Project structure:
  ```
  ./
    .docker/  --> Bridge for containerization logic.
    └── compose.yaml

    src/      --> App logic.
    └── Leaf
        ├── LeafHandler.php  --> Use Repository logic.
        ├── LeafHandlerInterface.php
        └── Repository
            ├── LeafRepository.php
            └── LeafRepositoryInterface.php

    uml/      --> Where to store a `.phar` file.
    └── umlwriter.phar
  ```  

  ```
  # File: .docker/compose.yaml
  services:
    cli:
        image: php:8.1.21-cli
        volumes:
            - ./../:/app
        working_dir: /app
  ```

## Hands on and output

I create a separate directory where to store the `.phar` file.

```
docker compose -f .docker/compose.yaml build

docker compose -f .docker/compose.yaml run --rm cli bash

apt-get update &&\
  apt-get upgrade -y &&\
  apt-get install -y\
    wget
    graphviz

# Download the "binary".
wget https://github.com/llaville/umlwriter/releases/download/3.4.0/umlwriter.phar

UML_TOOL=uml/umlwriter.phar

# Based on the documentation this is the way to go.
php $UML_TOOL diagram:class -vvv src/Leaf/

root@08c37f29a56d:/app# php $UML_TOOL diagram:class -vvv src/Leaf

Box Requirements Checker
========================

> Using PHP 8.1.21
> PHP is using the following php.ini file:
  WARNING: No configuration file (php.ini) used by PHP!

> Checking Box requirements:
  ✔ The application requires a version matching "^8.0".
  ✔ The application requires the extension "zlib".
  ✔ The package "jawira/plantuml-encoding" requires the extension "zlib".
  ✔ The package "nikic/php-parser" requires the extension "tokenizer".
  ✔ The package "roave/better-reflection" requires the extension "json".
  ✔ The package "symfony/service-contracts" conflicts with the extension "psr".


 [OK] Your system is ready to run the application.



UML Class Diagram Generation
============================

 --------------- ----------------------------------------------
  Path(s)         src/Leaf
  Generator       graphviz
  Configuration   Default values and/or command line arguments
 --------------- ----------------------------------------------


In ClassDiagramBuilder.php line 72:

  [ReflectionException (-1)]
  Class "src\Leaf\LeafHandler" does not exist


Exception trace:
  at phar:///app/uml/umlwriter.phar/vendor/bartlett/graph-uml/src/ClassDiagramBuilder.php:72
 ReflectionClass->__construct() at phar:///app/uml/umlwriter.phar/vendor/bartlett/graph-uml/src/ClassDiagramBuilder.php:72
 Bartlett\GraphUml\ClassDiagramBuilder->createVertexClass() at phar:///app/uml/umlwriter.phar/src/Service/ClassDiagramRenderer.php:62
 Bartlett\UmlWriter\Service\ClassDiagramRenderer->__invoke() at phar:///app/uml/umlwriter.phar/src/Console/Command/ClassDiagramCommand.php:120
 Bartlett\UmlWriter\Console\Command\ClassDiagramCommand->execute() at phar:///app/uml/umlwriter.phar/vendor/symfony/console/Command/Command.php:312
 Symfony\Component\Console\Command\Command->run() at phar:///app/uml/umlwriter.phar/vendor/symfony/console/Application.php:1022
 Symfony\Component\Console\Application->doRunCommand() at phar:///app/uml/umlwriter.phar/vendor/symfony/console/Application.php:314
 Symfony\Component\Console\Application->doRun() at phar:///app/uml/umlwriter.phar/src/Console/Application.php:93
 Bartlett\UmlWriter\Console\Application->doRun() at phar:///app/uml/umlwriter.phar/vendor/symfony/console/Application.php:168
 Symfony\Component\Console\Application->run() at phar:///app/uml/umlwriter.phar/src/Console/Application.php:124
 Bartlett\UmlWriter\Console\Application->run() at phar:///app/uml/umlwriter.phar/bin/umlwriter:52
 require() at /app/uml/umlwriter.phar:43

diagram:class [-o|--output OUTPUT] [--format FORMAT] [--generator GENERATOR] [--bootstrap BOOTSTRAP] [-c|--configuration CONFIGURATION] [--without-constants] [--without-properties] [--without-methods] [--hide-private] [--hide-protected] [--no-statement] [--] [<paths>...]
```

### References

- https://github.com/llaville/umlwriter/tree/master
- http://llaville.github.io/umlwriter/3.x/

<img width="1070" alt="Screen Shot 2023-08-04 at 9 01 46 PM" src="https://github.com/llaville/umlwriter/assets/45880759/9f034c16-f38a-4b88-974b-7ada8c3bc88c">

**Comment by llaville** [comment]
Hello,

First of all, you need to check if your application is running itself.
- that means that you've correctly installed it (and an autoloader is able to load all your classes)
- so, if you've installed your application with composer, that means that you should be able to have a "/app/vendor/autoload.php" file (into your container).

Then, and only if you're application is running you can try to build all UML diagrams you want. You need just to specifiy the autoloader to use with the `--bootstrap` option.

In your case, that means you have to invoke following command

`root@08c37f29a56d:/app# php $UML_TOOL diagram:class -vvv src/Leaf --bootstrap ./vendor/autoload.php`

Hope it will help !
