### ISSUE TITLE
sebastian/version 2.0

### ISSUE THREAD

**Issue by remicollet** [llaville/umlwriter#5]
Please allow it

       "sebastian/version": "^1.0 || ^2.0",

AFAIK, No API change

eg: https://github.com/sebastianbergmann/php-code-coverage/commit/95a0e74bc622c55a3aae76fdc9abd89c82fd4bc5

**Comment by llaville** [comment]
Sorry I can't accept yet the major version 2.0 that requires PHP 5.6 min, while UmlWriter is PHP 5.4 min
See https://github.com/sebastianbergmann/version/blob/master/composer.json#L17

**Comment by remicollet** [comment]
I don't understand what is the issue
People with php < 5.6 which still use version 1.0
People with php > 5.6 which still use version 2.0

This doesn't change anything

**Comment by llaville** [comment]
Sorry Remi, my apology to have misunderstood !

**Comment by remicollet** [comment]
Thanks
