### ISSUE TITLE
version 1.2.0 outputs invalid plantuml files

### ISSUE THREAD

**Issue by ziegi** [llaville/umlwriter#7]
Running php umlwriter-1.2.0.phar diagram:render --processor=plantuml PHP_FILE
i get plantuml code with the following errors:

interface TrackingDatabaseRepositoryInterface \ interface >> {
this line should read:
interface TrackingDatabaseRepositoryInterface << interface >> {

or
class BaseDatabaseRepositoryMysql \ class >> {
this line should read:
class BaseDatabaseRepositoryMysql << class >> {

this will fix the output:
php umlwriter-1.2.0.phar diagram:render --processor=plantuml PHP_FILE | sed 's/ \\ / << /g'

**Comment by llaville** [comment]
Please provide, source code analysed to reproduce this issue !
Don"t forget also to give what is your platform (linux / windows) and php version.

**Comment by ziegi** [comment]
PHP 7.1.15-1+ubuntu17.10.1+deb.sury.org+2
PlantUML Version 8040beta0
umlWriter version 1.2.0

steps to reproduce:
1. create php class file: simpleclass.php
```
<?php
declare(strict_types=1);
namespace ltta\model;
class BackupProject
{
    private $a;
   public function __construct(string  $a) 
    {
        $this->a = $a;
    }
}
```
2. run umlwriter: 

> php umlwriter-1.2.0.phar diagram:render --processor=plantuml simpleclass.php 

```
@startuml
namespace ltta.model  {
	class BackupProject \ class >> {
		-a
		--
		+__construct()
	}
}
@enduml
```
3. this can not be read by plantuml, but this can 

> php ../addons/umlwriter-1.2.0.phar diagram:render --processor=plantuml simpleclass.php | sed 's/ \\\\ / << /g'

```
@startuml
namespace ltta.model  {
	class BackupProject << class >> {
		-a
		--
		+__construct()
	}
}
@enduml
```

**Comment by llaville** [comment]
thanks; I will have a look later !

**Comment by llaville** [comment]
Ok I confirm it's an issue with release 1.2.0; previous version 1.1.0 did not produced such wrong results.

I'll have a look and apply a fix at the end of the week.
Thanks for reporting

**Comment by llaville** [comment]
Reason of this issue came from oudated dependencies : 

- version 1.2.0 used bartlett/php-reflect 4.0.2 (sep 2016) with nikic/php-parser 1.4.1

Bugfixe release 1.2.1 will use : 

- bartlett/php-reflect 4.2.2 (dec 2017) with nikic/php-parser 2.1.1

Symfony outdated will also raised to use at least version 3.4.x of components

**Comment by llaville** [comment]
Version 1.2.1 has just been released.
