### ISSUE TITLE
php7 compatibility

### ISSUE THREAD

**Issue by ziegi** [llaville/umlwriter#8]
I also find that it produces an empty diagram if the php7 keyword private const is used:
steps to reproduce:

create php class file: simpleclass.php
```
<?php
declare(strict_types=1);
class BackupProject
{
    private $a;
    private const B = 'b';
    public function __construct(string  $a) 
    {
        $this->a = $a;
    }
}
```
run umlwriter:
php umlwriter-1.2.0.phar diagram:render --processor=plantuml simpleclass.php
```
@startuml
@enduml
```

changing the php file and removing the private keyword from the const: simpleclass.php
```
<?php
declare(strict_types=1);
class BackupProject
{
    private $a;
    const B = 'b';
    public function __construct(string  $a) 
    {
        $this->a = $a;
    }
}
```
run umlwriter:
php umlwriter-1.2.0.phar diagram:render --processor=plantuml simpleclass.php
```
@startuml
	class BackupProject \ class >> {
		+B
		..
		-a
		--
		+__construct()
	}
@enduml
```

**Comment by llaville** [comment]
Well, when I've created this tool for the first times, PHP 7 was not available.

So the composer constraint `"php": ">=5.4.0"` did not match any PHP 7 versions. 
This is an error, and now with PHP 7, nobody did the same mistake.

In summary,  umlwriter is not compatible with PHP 7 code; I've in mind to make it possible, but I've no such free time to do it right now (it's a project).

**Comment by ziegi** [comment]
After a little debugging I found out, that the only problem seems to be, that the nikic/PHP-Parser
is used in a older version that does not support PHP 7.1

I managed to get PHP 7.1 compatibility using the following steps: 

1. In bartlett/umlwriter I changed to dependencies on bartlett/php-reflect to the newest version:
```
bartlett/umlwriter/composer.json:
@@ -15,7 +15,7 @@
         "sebastian/version": "^1.0|^2.0"
     },
     "require-dev": {
-        "bartlett/php-reflect": "^4.0",
+        "bartlett/php-reflect": "^4.2.2",
         "andrewsville/php-token-reflection": "^1.4"
     },
     "suggest": {
```
2. In bartlett/php-reflect I changed the dependencies on nikic/php-parser to the newest version and removed the php 5.5 platform restriction:
```
bartlett/php-reflect/composer.json:
@@ -25,7 +25,7 @@
         "ext-date": "*",
         "ext-reflection": "*",
         "sebastian/version": "^1.0|^2.0",
-        "nikic/php-parser": "^2.1",
+        "nikic/php-parser": "^4.0",
         "doctrine/collections": "^1.2",
         "symfony/event-dispatcher": "^2.5|^3.0",
         "symfony/finder": "^2.5|^3.0",
@@ -76,9 +76,6 @@
         }
     },
     "config": {
-        "platform": {
-            "php": "5.5.0"
-        },
         "optimize-autoloader": true
     }
 }
```
3. Then some minor modifications had to be done to get the bartlett/php-reflect code to be compatible with the new nikic/php-parser version:
```
bartlett/php-reflect/src/Bartlett/Reflect/Model/ClassModel.php
@@ -150,7 +150,7 @@
             foreach ($this->node->stmts as $stmt) {
                 if ($stmt instanceof Node\Stmt\ClassConst) {
                     foreach ($stmt->consts as $const) {
-                        $this->constants[$const->name] = trim(
+                        $this->constants[$const->name->name] = trim(  
                             $prettyPrinter->prettyPrintExpr($const->value),
                             '"\''
                         );
@@ -207,7 +207,7 @@
             foreach ($this->node->stmts as $stmt) {
                 if ($stmt instanceof Node\Stmt\ClassMethod) {
                     $stmt->setAttribute('fileName', $this->getFileName());
-                    $this->methods[$stmt->name] = new MethodModel($this, $stmt);
+                    $this->methods[$stmt->name->name] = new MethodModel($this, $stmt);
                 }
             }
         }

```

this fixed for me the problems with class private consts,
I hope it did not break other things.

**Comment by Josee9988** [comment]
`umlwriter diagram:render --processor=graphviz src/Entity/Comerciales.php ` gives:

``` Bash
digraph G {
	overlap = false;
	node [fontname="Verdana", fontsize="8", shape="none", margin="0", fillcolor="#FEFECE", style="filled"];
	edge [fontname="Verdana", fontsize="8"];
}
```

I'm using symfony 4.4 and i'd love to use your tool... @llaville

**Comment by llaville** [comment]
A 1.4.0 release could be considered to fix it, but i've in mind a new major version 2.0 that solved it and allow more Reflection providers that just PHP_Reflect.

**Comment by llaville** [comment]
Version 1.4.0 won't never exists. 

Major version 2.0 is under writing, and will drop dependency to PHP_Reflect or anyother external reflection engine.
I've wrote a simple parser reflection that will be include in first alpha version, just to have users feedback !
This parser of course is based on nikic/PHP_Parser v4. That will solve all PHP 7 syntax issues detected with current umlWriter version !

**Comment by llaville** [comment]
the first alpha version of major 2.0 will be released in next days.
graph will be handled by graphp/graph and graphp/graphviz packages (dev-master branch). latest versions published are not enough.
2.0-alpha 1 will also include a lite php parser reflection that should be externalized when we reach beta stage

**Comment by llaville** [comment]
I won't publish my lite parser reflection, because there are no need to create a new package that have base features of https://github.com/goaop/parser-reflection
So I will used this one instead of mine solution !
I will release the first alpha of v2.0 tomorrow.

**Comment by llaville** [comment]
Quick new: i've published today https://github.com/llaville/graph-uml that is able to produce UML class diagram.  Format is only GraphViz, but a PlantUML version will come soon.
UmlWriter 2.0 will then be a simple facade to simplify parsing a folder or just one file around this graph-uml version.

**Comment by llaville** [comment]
As I've reach an important milestone with https://github.com/llaville/graph-uml 0.3.0 (just released), I'm now able to publish UmlWriter 2.0.0-beta1 that will accept only GraphViz backend.

Next releases will come with support of PlantUML and much more.

**Comment by llaville** [comment]
First pre-release version is available on packagist and on [branch 2.x](https://github.com/llaville/umlwriter/tree/2.x)

**Comment by llaville** [comment]
@ziegi @Josee9988 Any feedback of the new major version is welcome !

**Comment by llaville** [comment]
2.0.0-beta.2 has just been released with support of PlantUML. See [examples folder](https://github.com/llaville/umlwriter/tree/2.x/examples) of branch 2.x

At least one other beta (to add option to personalize render easily) before first RC

**Comment by Josee9988** [comment]
> @ziegi @Josee9988 Any feedback of the new major version is welcome !

How do I download the newest beta version with composer? Seems like I'm only able to download the 1.3 version

**Comment by ziegi** [comment]
I have got this section in my composer.json
without the graphp and symfony lines
the dependencies will not allow the dev versions
required by umlwriter

"bartlett/umlwriter": "2.x-dev",
"graphp/graph": "dev-master",
"graphp/graphviz": "dev-master",
"symfony/finder": "^5.0"

Am 10.05.20 um 18:56 schrieb Jose Gracia Berenguer:

**Comment by llaville** [comment]
Reason is that you should use my [fork of graphviz](https://github.com/llaville/graphviz) that did not include/support yet the subgraph/cluster attributes (see my branch: *subgraph_cluster_attributes*).
I've closed my PR https://github.com/graphp/graphviz/pull/44, due to lack of interest !

So in your composer.json you must have:  
```json
{
    "require": {
        "bartlett/umlwriter": "2.x-dev",
        "graphp/graph": "dev-master",
        "graphp/graphviz": "dev-subgraph_cluster_attributes",
        "symfony/finder": "^5.0"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/llaville/graphviz"
        }
    ]
}
```

**Comment by llaville** [comment]
https://github.com/llaville/graph-uml as reached a stable step in development (v0.8.0) with a better support of subgraph cluster attributes. Next step is the first Release Candidate !

https://github.com/llaville/graph-plantuml-generator as almost reached a stable step in development (0.3.0). Need again some unit tests and documentation. Next step is the first RC !

UmlWriter will reach tomorrow a features frozen state in developement of next major version 2.0
After a 2.0.0-beta.3 that need documentation rewrites and unit tests, next step will be the first RC !

To all contributors and users, this is your last chance to give a feedback !

**Comment by llaville** [comment]
2.0.0-rc.1 has just been released. I'll close now this report. 
If you find issues about v2, please open new issue reports.
